language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1

before_install: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer install --dev

script: vendor/bin/phpunit -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
